"""add cloudinary fields

Revision ID: a6981c18c68a
Revises: b1c99788e733
Create Date: 2026-06-15 15:46:50.465024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6981c18c68a'
down_revision: Union[str, Sequence[str], None] = 'b1c99788e733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'cloudinary_public_id')
    op.drop_column('documents', 'cloudinary_url')
    # ### end Alembic commands ###
