"""remove cloudinary fields

Revision ID: b37df152f343
Revises: a6981c18c68a
Create Date: 2026-06-17 22:52:10.872852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37df152f343'
down_revision: Union[str, Sequence[str], None] = 'a6981c18c68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'cloudinary_public_id')
    op.drop_column('documents', 'cloudinary_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('cloudinary_public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
